services:
  myapp2:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: myapp2_frontend
    hostname: myapp2_frontend
    env_file:
      - ./client/.env
    ports:
      - '4003:5173'
    restart: always

networks:
  default:
    name: nginx_tier
    external: true
